ENV['VAGRANT_NO_PARALLEL'] = 'yes'

CONFIG_WAN_NETWORK = '10.0.10.0'
CONFIG_LAN_NETWORK = '10.0.20.0'
CONFIG_LAN_IP      = '10.0.20.254'
CONFIG_LAN_NETMASK = '255.255.255.0'

CONFIG_DEFAULT_PREFIX   = "#{File.basename(File.dirname(File.dirname(__FILE__)))}-"
CONFIG_WAN_NETWORK_NAME = "#{CONFIG_DEFAULT_PREFIX}-wan"
CONFIG_LAN_NETWORK_NAME = "#{CONFIG_DEFAULT_PREFIX}-lan"

CONFIG_DEBIAN_MAC   = '08:00:27:00:00:0a'
CONFIG_DEBIAN_IP    = '10.0.20.10'
CONFIG_UBUNTU_MAC   = '08:00:27:00:00:0b'
CONFIG_UBUNTU_IP    = '10.0.20.11'
CONFIG_WINDOWS_MAC  = '08:00:27:00:00:0c'
CONFIG_WINDOWS_IP   = '10.0.20.12'

Vagrant.configure(2) do |config|
  config.vm.provider 'libvirt' do |lv, config|
    lv.default_prefix = CONFIG_DEFAULT_PREFIX
    lv.cpus = 2
    lv.cpu_mode = 'host-passthrough'
    #lv.nested = true # nested virtualization.
    lv.keymap = 'pt'
  end

  config.vm.define :openwrt do |config|
    config.vm.box = 'openwrt-22.03-amd64'
    #config.vm.box = 'openwrt-22.03-uefi-amd64'
    config.vm.hostname = 'openwrt.lan'
    config.vm.provider 'libvirt' do |lv, config|
      lv.memory = 2*1024
      config.vm.network :private_network,
        ip: CONFIG_WAN_NETWORK,
        auto_config: false,
        libvirt__network_name: CONFIG_WAN_NETWORK_NAME,
        libvirt__dhcp_enabled: true,
        libvirt__forward_mode: 'nat'
      config.vm.network :private_network,
        ip: CONFIG_LAN_NETWORK,
        auto_config: false,
        libvirt__network_name: CONFIG_LAN_NETWORK_NAME,
        libvirt__dhcp_enabled: false,
        libvirt__forward_mode: 'none'
      #config.vm.synced_folder '.', '/vagrant', disabled: true
      config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: [
        '.vagrant/',
        '.git/',
        '*.box']
    end
    config.vm.provision 'shell', inline: 'echo "firmware type is $([ -d /sys/firmware/efi ] && echo \'UEFI\' || echo \'BIOS\')"', name: 'firmware type'
    config.vm.provision 'shell', inline: 'sfdisk -l', name: 'disk partitions'
    config.vm.provision 'shell', inline: 'lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL', name: 'block devices'
    config.vm.provision 'shell', inline: 'df -h', name: 'disk space usage'
    config.vm.provision 'shell', inline: "opkg list-installed >/vagrant/#{config.vm.box}-packages.txt", name: 'package list'
    config.vm.provision 'shell', path: 'provision-openwrt.sh', args: [
      CONFIG_LAN_IP,
      CONFIG_LAN_NETMASK,
      CONFIG_DEBIAN_MAC,
      CONFIG_DEBIAN_IP,
      CONFIG_UBUNTU_MAC,
      CONFIG_UBUNTU_IP,
      CONFIG_WINDOWS_MAC,
      CONFIG_WINDOWS_IP
    ]
    # install docker.
    # see https://openwrt.org/docs/guide-user/virtualization/docker_host
    config.vm.provision 'shell', inline: 'opkg update && opkg install dockerd docker luci-app-dockerman && service rpcd restart', name: 'install docker'
    config.vm.provision 'shell', inline: 'docker run --rm --net=host ruilopes/example-docker-buildx-go:v1.10.0', name: 'run a container'
    # install netbird.
    config.vm.provision 'shell', path: 'provision-netbird.sh', env: {'NETBIRD_SETUP_KEY' => ENV['NETBIRD_SETUP_KEY']}, name: 'install netbird'
  end

  config.vm.define :debian do |config|
    config.vm.box = 'debian-12-amd64'
    config.vm.hostname = 'debian.lan'
    config.vm.provider 'libvirt' do |lv, config|
      lv.memory = 512
      lv.qemu_use_agent = true
      lv.management_network_name = CONFIG_LAN_NETWORK_NAME
      lv.management_network_mac = CONFIG_DEBIAN_MAC
      config.vm.synced_folder '.', '/vagrant', disabled: true
    end
    config.vm.provision 'shell', inline: 'apt-get update && apt-get install -y tcpdump dnsutils', name: 'install tools'
    config.vm.provision 'shell', path: 'provision-netbird-debian.sh', env: {'NETBIRD_SETUP_KEY' => ENV['NETBIRD_SETUP_KEY']}, name: 'install netbird'
  end

  config.vm.define :ubuntu do |config|
    config.vm.box = 'ubuntu-22.04-amd64'
    config.vm.hostname = 'ubuntu.lan'
    config.vm.provider 'libvirt' do |lv, config|
      lv.memory = 1024
      lv.qemu_use_agent = true
      lv.management_network_name = CONFIG_LAN_NETWORK_NAME
      lv.management_network_mac = CONFIG_UBUNTU_MAC
      config.vm.synced_folder '.', '/vagrant', disabled: true
    end
    config.vm.provision 'shell', inline: 'apt-get update && apt-get install -y tcpdump dnsutils', name: 'install tools'
    config.vm.provision 'shell', path: 'provision-netbird-debian.sh', env: {'NETBIRD_SETUP_KEY' => ENV['NETBIRD_SETUP_KEY']}, name: 'install netbird'
  end

  config.vm.define :windows do |config|
    config.vm.box = 'windows-2022-amd64'
    config.vm.hostname = 'windows'
    config.vm.provider 'libvirt' do |lv, config|
      lv.memory = 2*1024
      lv.qemu_use_agent = true
      lv.management_network_name = CONFIG_LAN_NETWORK_NAME
      lv.management_network_mac = CONFIG_WINDOWS_MAC
      config.vm.synced_folder '.', '/vagrant', disabled: true
    end
    config.vm.provision 'shell', path: 'provision-netbird-windows.ps1', env: {'NETBIRD_SETUP_KEY' => ENV['NETBIRD_SETUP_KEY']}, name: 'install netbird'
  end
end
